version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro

# Optional: Define volumes for persistent data (if needed in future)
volumes:
  nginx_logs:
    driver: local
